/* Function ifstmt
Parses strings in the language generated by the rule:
<ifstmt> -> if (<boolexpr>) <statement>
[else <statement>]
*/
void ifstmt() {
    /* Be sure the first token is 'if' */
    if (nextToken != IF_CODE)
        error();
    else {
        /* Call lex to get to the next token */
        lex();
        /* Check for the left parenthesis */
        if (nextToken != LEFT_PAREN)
        error();
        else {
            /* Call boolexpr to parse the Boolean expression */
            boolexpr();
            /* Check for the right parenthesis */
            if (nextToken != RIGHT_PAREN)
                error();
            else {
                /* Call statement to parse the then clause */
                statement();
                /* If an else is next, parse the else clause */
                if (nextToken == ELSE_CODE) {
                    /* Call lex to get over the else */
                    lex();
                    statement();
                } /* end of if (nextToken == ELSE_CODE ... */
            } /* end of else of if (nextToken != RIGHT ... */
        } /* end of else of if (nextToken != LEFT ... */
    } /* end of else of if (nextToken != IF_CODE ... */
} /* end of ifstmt */